server:
  port: 8082
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:transferdb
    username: fmetin
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
rabbitmq:
  shutDownQueue:
    name: shut_down_queue
  exchange:
    name: darkstore_exchange
  shutDown:
    routing:
      key: shut_down_routing_key