spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:depotdb
    username: fmetin
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME:localhost}
redis:
  hostname: ${REDIS_HOSTNAME:localhost}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
rabbitmq:
  shutDownQueue:
    name: shut_down_queue
  exchange:
    name: darkstore_exchange
  shutDown:
    routing:
      key: shut_down_routing_key
